### 1.3 배열의 연산(Operation)

In [2]:
import numpy as np

- 벡터화 연산

In [3]:
x = np.arange(1, 100001)
y = np.arange(100001, 200001)

In [4]:
%%time
z = np.empty_like(x)
for i in range(100000):
    z[i] = x[i] + y[i]

CPU times: total: 46.9 ms
Wall time: 46 ms


In [5]:
%%time 
z = x + y

CPU times: total: 0 ns
Wall time: 0 ns


In [6]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
a == b

array([False,  True, False,  True])

In [7]:
a >= b

array([False,  True,  True,  True])

In [8]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [9]:
10 ** a

array([   10,   100,  1000, 10000], dtype=int32)

In [10]:
5 * a

array([ 5, 10, 15, 20])

In [11]:
5 + a

array([6, 7, 8, 9])

- 차원 축소 연산

In [12]:
x = np.arange(1,5)
np.sum(x)

10

In [13]:
x.sum()

10

In [14]:
x.min(), x.max(), x.mean()      #최소, 최대, 평균

(1, 4, 2.5)

In [15]:
# 대표값: 평균, 중앙값
np.mean(x), np.median(x)

(2.5, 2.5)

In [16]:
# 통계: 분산, 표준편차 
np.var(x), np.std(x)

(1.25, 1.118033988749895)

In [17]:
#최소값, 최대값의 인덱스
x.argmin(), x.argmax()

(0, 3)

- all/ any

In [18]:
np.all(np.array([True, True, False])), np.any(np.array([True, True, False]))

(False, True)

In [19]:
np.all (a == a)

True

- 2차원 이상의 연산

In [20]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# 모든 원소의 합과 평균
np.sum(a), np.mean(a)

(21, 3.5)

In [22]:
# axis = 0, 각 좌표(row, col)에서 row를 변경시켜가면서 액세스
np.sum(a, axis=0), np.mean(a, axis=0)

(array([5, 7, 9]), array([2.5, 3.5, 4.5]))

In [23]:
# axis = 1, 각 좌표(row, col)에서 col을 변경시켜가면서 액세스
np.sum(a, axis=1), np.mean(a, axis=1)

(array([ 6, 15]), array([2., 5.]))

In [24]:
b = np.arange(1, 13).reshape(2, 2, -1)
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
np.sum(b, axis=0)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [26]:
np.sum(b, axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

In [27]:
np.sum(b, axis=2)

array([[ 6, 15],
       [24, 33]])

- 연습문제 3.3.1

In [28]:
np.random.seed(2023)
x = np.round(np.random.random(30).reshape(5,6) * 10, 4)
x

array([[0.4744, 2.4991, 4.2237, 5.8104, 8.6101, 9.2863],
       [6.4109, 7.8722, 4.6659, 8.1283, 9.8029, 3.5741],
       [8.8887, 7.0848, 1.9221, 9.055 , 4.5063, 8.2499],
       [2.6387, 9.8891, 5.3195, 1.5849, 6.9387, 6.2011],
       [7.5396, 7.4337, 1.0016, 7.6953, 2.6349, 0.0935]])

In [29]:
#전체의 최댓값
np.max(x)           #x.max()

9.8891

In [30]:
#각 행의 합
np.sum(x, axis=1)   #x.sum(axis=1)

array([30.904 , 40.4543, 39.7068, 32.572 , 26.3986])

In [31]:
#각 행의 최댓값
np.max(x, axis=1)    #x.max(axis=1)

array([9.2863, 9.8029, 9.055 , 9.8891, 7.6953])

In [32]:
#각 열의 평균
np.mean(x, axis=0)        #x.mean(axis=0)

array([5.19046, 6.95578, 3.42656, 6.45478, 6.49858, 5.48098])

In [33]:
#각 열의 최솟값
np.min(x, axis=0)       #x.min(axis=0)

array([0.4744, 2.4991, 1.0016, 1.5849, 2.6349, 0.0935])

- 정렬(sort)

In [34]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [35]:
np.sort(a)      #default axis=1

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [36]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [37]:
# 내림차순 정렬, axis=1인 경우
np.sort(a, axis=1)[:, ::-1]

array([[ 7,  5,  4,  3],
       [12, 11,  9,  1],
       [15, 14,  2,  1]])

In [38]:
# 내림차순 정렬, axis=0인 경우
np.sort(a, axis=0)[::-1, :]

array([[ 4, 15, 11, 14],
       [ 2, 12,  5,  9],
       [ 1,  3,  1,  7]])

In [39]:
# sort() method는 자기 파괴적
a.sort(axis=1)

In [40]:
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [41]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [42]:
a[j]

array([12, 25, 38, 42])

- 연습문제 3.3.2

In [43]:
score = np.array([[1, 2, 3, 4],         #학번
                [46, 99, 100, 71],      #영어
                [81, 59, 90, 100]])     #수학
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [46]:
# 영어 성적을 argsort() 하여 인덱스를 구함
indices = np.argsort(score[1])  # 인덱스 순서가 오름차순으로 정렬됨
indices

array([0, 3, 1, 2], dtype=int64)

In [47]:
# 인덱스를 내림차순을 정렬
indices[::-1]

array([2, 1, 3, 0], dtype=int64)

In [49]:
# 모든 행을 영어성적 내림차순으로 정렬
score[:, indices[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [50]:
# 한 줄로
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])